//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.21 at 07:35:22 PM CEST 
//


package com.car_rent.agent_api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.car_rent.agent_api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.car_rent.agent_api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteBookingResponse }
     * 
     */
    public DeleteBookingResponse createDeleteBookingResponse() {
        return new DeleteBookingResponse();
    }

    /**
     * Create an instance of {@link ReserveBookingRequest }
     * 
     */
    public ReserveBookingRequest createReserveBookingRequest() {
        return new ReserveBookingRequest();
    }

    /**
     * Create an instance of {@link BundleDetails }
     * 
     */
    public BundleDetails createBundleDetails() {
        return new BundleDetails();
    }

    /**
     * Create an instance of {@link GetBookingsRequest }
     * 
     */
    public GetBookingsRequest createGetBookingsRequest() {
        return new GetBookingsRequest();
    }

    /**
     * Create an instance of {@link CheckingBookingRequest }
     * 
     */
    public CheckingBookingRequest createCheckingBookingRequest() {
        return new CheckingBookingRequest();
    }

    /**
     * Create an instance of {@link RejectBookingResponse }
     * 
     */
    public RejectBookingResponse createRejectBookingResponse() {
        return new RejectBookingResponse();
    }

    /**
     * Create an instance of {@link AcceptBookingResponse }
     * 
     */
    public AcceptBookingResponse createAcceptBookingResponse() {
        return new AcceptBookingResponse();
    }

    /**
     * Create an instance of {@link AcceptBookingRequest }
     * 
     */
    public AcceptBookingRequest createAcceptBookingRequest() {
        return new AcceptBookingRequest();
    }

    /**
     * Create an instance of {@link RejectBookingRequest }
     * 
     */
    public RejectBookingRequest createRejectBookingRequest() {
        return new RejectBookingRequest();
    }

    /**
     * Create an instance of {@link CheckingBookingResponse }
     * 
     */
    public CheckingBookingResponse createCheckingBookingResponse() {
        return new CheckingBookingResponse();
    }

    /**
     * Create an instance of {@link ReserveBookingResponse }
     * 
     */
    public ReserveBookingResponse createReserveBookingResponse() {
        return new ReserveBookingResponse();
    }

    /**
     * Create an instance of {@link DeleteBookingRequest }
     * 
     */
    public DeleteBookingRequest createDeleteBookingRequest() {
        return new DeleteBookingRequest();
    }

    /**
     * Create an instance of {@link GetBookingsResponse }
     * 
     */
    public GetBookingsResponse createGetBookingsResponse() {
        return new GetBookingsResponse();
    }

    /**
     * Create an instance of {@link BookingDetails }
     * 
     */
    public BookingDetails createBookingDetails() {
        return new BookingDetails();
    }

    /**
     * Create an instance of {@link BookDetails }
     * 
     */
    public BookDetails createBookDetails() {
        return new BookDetails();
    }

}
