server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        addToSimpleUrlHandlerMapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
            exposeHeaders: 'Authorization'
      discovery:
        locator:
          enabled: true
      routes:
        - id: cars-ads
          uri: 'lb://cars-ads'
          predicates:
            - Path=/cars-ads/**
          filters:
            - 'RewritePath=/cars-ads/(?<path>.*), /$\{path}'
        - id: cars
          uri: 'lb://cars'
          predicates:
            - Path=/cars/**
          filters:
            - 'RewritePath=/cars/(?<path>.*), /$\{path}'
        - id: rent
          uri: 'lb://rent'
          predicates:
            - Path=/rent/**
          filters:
            - 'RewritePath=/rent/(?<path>.*), /$\{path}'
        - id: user
          uri: 'lb://user'
          predicates:
            - Path=/user/**
          filters:
            - 'RewritePath=/user/(?<path>.*), /$\{path}'
        - id: codebook
          uri: 'lb://codebook'
          predicates:
            - Path=/codebook/**
          filters:
            - 'RewritePath=/codebook/(?<path>.*), /$\{path}'
