//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.12 at 01:39:31 PM CEST 
//


package com.car_rent.agent_api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="updateCarDetails" type="{http://car-rent.com/agent-api}UpdateCarDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "updateCarDetails"
})
@XmlRootElement(name = "editCarRequest")
public class EditCarRequest {

    protected long id;
    @XmlElement(required = true)
    protected UpdateCarDetails updateCarDetails;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the updateCarDetails property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateCarDetails }
     *     
     */
    public UpdateCarDetails getUpdateCarDetails() {
        return updateCarDetails;
    }

    /**
     * Sets the value of the updateCarDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateCarDetails }
     *     
     */
    public void setUpdateCarDetails(UpdateCarDetails value) {
        this.updateCarDetails = value;
    }

}
