//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.08 at 09:00:03 PM CEST 
//


package com.car_rent.agent_api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.car_rent.agent_api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.car_rent.agent_api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EditCarResponse }
     * 
     */
    public EditCarResponse createEditCarResponse() {
        return new EditCarResponse();
    }

    /**
     * Create an instance of {@link EditCarRequest }
     * 
     */
    public EditCarRequest createEditCarRequest() {
        return new EditCarRequest();
    }

    /**
     * Create an instance of {@link UpdateCarDetails }
     * 
     */
    public UpdateCarDetails createUpdateCarDetails() {
        return new UpdateCarDetails();
    }

    /**
     * Create an instance of {@link EditAdRequest }
     * 
     */
    public EditAdRequest createEditAdRequest() {
        return new EditAdRequest();
    }

    /**
     * Create an instance of {@link AdFormDetails }
     * 
     */
    public AdFormDetails createAdFormDetails() {
        return new AdFormDetails();
    }

    /**
     * Create an instance of {@link CreateAdRequest }
     * 
     */
    public CreateAdRequest createCreateAdRequest() {
        return new CreateAdRequest();
    }

    /**
     * Create an instance of {@link GetAdsResponse }
     * 
     */
    public GetAdsResponse createGetAdsResponse() {
        return new GetAdsResponse();
    }

    /**
     * Create an instance of {@link AdDetails }
     * 
     */
    public AdDetails createAdDetails() {
        return new AdDetails();
    }

    /**
     * Create an instance of {@link CreateCarRequest }
     * 
     */
    public CreateCarRequest createCreateCarRequest() {
        return new CreateCarRequest();
    }

    /**
     * Create an instance of {@link CarDetails }
     * 
     */
    public CarDetails createCarDetails() {
        return new CarDetails();
    }

    /**
     * Create an instance of {@link GetCarsResponse }
     * 
     */
    public GetCarsResponse createGetCarsResponse() {
        return new GetCarsResponse();
    }

    /**
     * Create an instance of {@link CarDetailsSoap }
     * 
     */
    public CarDetailsSoap createCarDetailsSoap() {
        return new CarDetailsSoap();
    }

    /**
     * Create an instance of {@link DeactivateAdRequest }
     * 
     */
    public DeactivateAdRequest createDeactivateAdRequest() {
        return new DeactivateAdRequest();
    }

    /**
     * Create an instance of {@link UpdateCarImagesRequest }
     * 
     */
    public UpdateCarImagesRequest createUpdateCarImagesRequest() {
        return new UpdateCarImagesRequest();
    }

    /**
     * Create an instance of {@link GetAdsRequest }
     * 
     */
    public GetAdsRequest createGetAdsRequest() {
        return new GetAdsRequest();
    }

    /**
     * Create an instance of {@link ActivateAdResponse }
     * 
     */
    public ActivateAdResponse createActivateAdResponse() {
        return new ActivateAdResponse();
    }

    /**
     * Create an instance of {@link DeleteCarResponse }
     * 
     */
    public DeleteCarResponse createDeleteCarResponse() {
        return new DeleteCarResponse();
    }

    /**
     * Create an instance of {@link ActivateAdRequest }
     * 
     */
    public ActivateAdRequest createActivateAdRequest() {
        return new ActivateAdRequest();
    }

    /**
     * Create an instance of {@link CreateAdResponse }
     * 
     */
    public CreateAdResponse createCreateAdResponse() {
        return new CreateAdResponse();
    }

    /**
     * Create an instance of {@link EditAdResponse }
     * 
     */
    public EditAdResponse createEditAdResponse() {
        return new EditAdResponse();
    }

    /**
     * Create an instance of {@link UpdateCarImagesResponse }
     * 
     */
    public UpdateCarImagesResponse createUpdateCarImagesResponse() {
        return new UpdateCarImagesResponse();
    }

    /**
     * Create an instance of {@link DeactivateAdResponse }
     * 
     */
    public DeactivateAdResponse createDeactivateAdResponse() {
        return new DeactivateAdResponse();
    }

    /**
     * Create an instance of {@link CreateCarResponse }
     * 
     */
    public CreateCarResponse createCreateCarResponse() {
        return new CreateCarResponse();
    }

    /**
     * Create an instance of {@link GetCarsRequest }
     * 
     */
    public GetCarsRequest createGetCarsRequest() {
        return new GetCarsRequest();
    }

    /**
     * Create an instance of {@link DeleteCarRequest }
     * 
     */
    public DeleteCarRequest createDeleteCarRequest() {
        return new DeleteCarRequest();
    }

    /**
     * Create an instance of {@link ImageDetails }
     * 
     */
    public ImageDetails createImageDetails() {
        return new ImageDetails();
    }

}
