//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
<<<<<<< HEAD
// Generated on: 2020.07.12 at 06:56:02 AM CEST 
=======
// Generated on: 2020.07.12 at 04:49:14 AM CEST 
>>>>>>> master
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://car-rent.com/agent-api", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.car_rent.agent_api;
