//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.07.12 at 10:58:59 AM CEST 
//


package com.car_rent.agent_api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.car_rent.agent_api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.car_rent.agent_api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateReportResponse }
     * 
     */
    public CreateReportResponse createCreateReportResponse() {
        return new CreateReportResponse();
    }

    /**
     * Create an instance of {@link CreateMessageResponse }
     * 
     */
    public CreateMessageResponse createCreateMessageResponse() {
        return new CreateMessageResponse();
    }

    /**
     * Create an instance of {@link MessageDetails }
     * 
     */
    public MessageDetails createMessageDetails() {
        return new MessageDetails();
    }

    /**
     * Create an instance of {@link ReplyResponse }
     * 
     */
    public ReplyResponse createReplyResponse() {
        return new ReplyResponse();
    }

    /**
     * Create an instance of {@link ReplyRequest }
     * 
     */
    public ReplyRequest createReplyRequest() {
        return new ReplyRequest();
    }

    /**
     * Create an instance of {@link StartConversationResponse }
     * 
     */
    public StartConversationResponse createStartConversationResponse() {
        return new StartConversationResponse();
    }

    /**
     * Create an instance of {@link GetRatesResponse }
     * 
     */
    public GetRatesResponse createGetRatesResponse() {
        return new GetRatesResponse();
    }

    /**
     * Create an instance of {@link RateDetails }
     * 
     */
    public RateDetails createRateDetails() {
        return new RateDetails();
    }

    /**
     * Create an instance of {@link CreateMessageRequest }
     * 
     */
    public CreateMessageRequest createCreateMessageRequest() {
        return new CreateMessageRequest();
    }

    /**
     * Create an instance of {@link CreateReportRequest }
     * 
     */
    public CreateReportRequest createCreateReportRequest() {
        return new CreateReportRequest();
    }

    /**
     * Create an instance of {@link ReportDetails }
     * 
     */
    public ReportDetails createReportDetails() {
        return new ReportDetails();
    }

    /**
     * Create an instance of {@link GetConversationRequest }
     * 
     */
    public GetConversationRequest createGetConversationRequest() {
        return new GetConversationRequest();
    }

    /**
     * Create an instance of {@link GetReportsRequest }
     * 
     */
    public GetReportsRequest createGetReportsRequest() {
        return new GetReportsRequest();
    }

    /**
     * Create an instance of {@link GetPeopleResponse }
     * 
     */
    public GetPeopleResponse createGetPeopleResponse() {
        return new GetPeopleResponse();
    }

    /**
     * Create an instance of {@link GetReportsResponse }
     * 
     */
    public GetReportsResponse createGetReportsResponse() {
        return new GetReportsResponse();
    }

    /**
     * Create an instance of {@link StartConversationRequest }
     * 
     */
    public StartConversationRequest createStartConversationRequest() {
        return new StartConversationRequest();
    }

    /**
     * Create an instance of {@link GetConversationResponse }
     * 
     */
    public GetConversationResponse createGetConversationResponse() {
        return new GetConversationResponse();
    }

    /**
     * Create an instance of {@link GetRatesRequest }
     * 
     */
    public GetRatesRequest createGetRatesRequest() {
        return new GetRatesRequest();
    }

    /**
     * Create an instance of {@link GetPeopleRequest }
     * 
     */
    public GetPeopleRequest createGetPeopleRequest() {
        return new GetPeopleRequest();
    }

}
